version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "hexagonal:${DATASOURCE_USERNAME}"
      POSTGRES_PASSWORD: "api:${DATASOURCE_PASSWORD}"
      POSTGRES_DB: "api:${DATASOURCE_DB}"
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080