--liquibase formatted sql

--changeset ito:1620678074101-1
CREATE SEQUENCE  IF NOT EXISTS hibernate_sequence;

--changeset ito:1620678074101-2
CREATE TABLE student (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, CONSTRAINT "studentPK" PRIMARY KEY (id));

